### ISSUE TITLE
How do I issue commands to open/close the boom barrier with V2000 controller?

### ISSUE THREAD

**Issue by cuisineje** [lixmk/Concierge#3]
Hi there
Greatly appreciated if uyou can help me with this. How do I open the boom barrier which is fitted with V2000 controlelr over network (ethernet). Preferably curl commands with URLs
tx
Raj

**Comment by alset333** [comment]
I don't know about that specifically, but most of this software is relatively straightforward. If that system is supported, I would assume you can just "unlock" it like the other controllers.
If you want to use curl, my suggestion would be get the code working, then look at what is actually happening for the networking (Yay open source)

**Comment by lixmk** [comment]
First, it's important to remember that the HID EVO scripts exploit a vulnerability and not a standard way of operating controller equipment. If the target controller is patched, they won't work. I've never tested a boom. It's possible that they use the controllers Aux relay's instead of standard strike relays. If so, this code does not support that.

The easiest route, assuming you have actual legitimate access, is to log into the controller's web management portal (port 80, default username `admin` with no password) and use the buttons on the status page to open the boom. Once you've found exactly which button does it, you can copy the POST and resend via curl.

Closing this issue as it isn't related to the code.

**Comment by cuisineje** [comment]
thank you for your responses. Highly appreciated
